refactor: Fix null check and implicit any
microsoft/vscode-java-dependency pull request #389
Opened 2020-11-24 03:30 UTC by xqzlgy2

This PR enabled TS compiler check for:

- Strict null check
- Implicit any

Also fixed existing errors.

#368

2020-12-04 08:03 UTC, jdneo requested changes

2020-12-04 09:05 UTC, xqzlgy2 commented on src/views/projectNode.ts
> +                        const packages: INodeData[][] = [];
currently seems not

2020-12-05 06:12 UTC, jdneo commented on src/explorerCommands/rename.ts
> +    if (!node.uri) {
redundant code

2020-12-08 05:25 UTC, jdneo requested changes

2020-12-08 05:25 UTC, jdneo commented on src/explorerCommands/new.ts
> +            if (packageNode && packageNode.uri) {
`if (packageNode?.uri)`

2020-12-08 05:25 UTC, jdneo commented on src/java/hierarchicalPackageNodeData.ts
> +    private nodeData?: INodeData = undefined;
`private nodeData?: INodeData;`

2020-12-08 05:25 UTC, jdneo commented on src/views/PrimaryTypeNode.ts
> +        switch (this.nodeData.metaData![PrimaryTypeNode.K_TYPE_KIND]) {
`this.nodeData.metaData?.[PrimaryTypeNode.K_TYPE_KIND]`

2020-12-08 05:25 UTC, jdneo commented on src/views/hierarchicalPackageRootNode.ts
> +        const hierarchicalPackageNodes = this.getHierarchicalPackageNodes();
`return result.concat(hierarchicalPackageNodes)`

2020-12-08 05:28 UTC, jdneo commented on src/views/hierarchicalPackageRootNode.ts
> +        return hierarchicalPackageNodeData === undefined ? [] : hierarchicalPackageNodeData.children.map((hierarchicalChildrenNode) =>
```
return hierarchicalPackageNodeData?.children.map(...) || [];
```

2020-12-09 02:43 UTC, jdneo requested changes

2020-12-09 02:43 UTC, jdneo commented on src/exportJarSteps/ExportJarTaskProvider.ts
> +                const projectList: INodeData[] | undefined = await Jdtls.getProjects(this.stepMetadata.workspaceFolder!.uri.toString()) || [];
`!` no need here

2020-12-09 03:09 UTC, jdneo approved these changes
Thanks @xqzlgy2

2020-12-09 03:09 UTC, merged